repos:
-   repo: local
    hooks:
    -   id: isort
        name: Isort
        description: Sorts the imports of this repository using isort.
        entry: pipenv run isort .
        language: python
        types: [python]
        require_serial: true
    -   id: black
        name: Black
        description: Format the code of this repository using black.
        entry: pipenv run black .
        language: python
        types: [python]
        require_serial: true
    -   id: flake8
        name: Flake8
        description: Lints this repository using flake8.
        entry: pipenv run flake8 .
        language: python
        types: [python]
        require_serial: true
